# Generated by Django 4.1 on 2022-11-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0004_faq_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='username',
            field=models.CharField(max_length=250),
        ),
    ]
