# Generated by Django 4.1 on 2022-11-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_userprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
