# Generated by Django 4.1 on 2022-12-12 10:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_lastedited_password_edited_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastedited',
            name='last_username_edited',
        ),
        migrations.RemoveField(
            model_name='lastedited',
            name='username_edited',
        ),
        migrations.AlterField(
            model_name='lastedited',
            name='last_password_edited',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
