# Generated by Django 4.1 on 2022-10-26 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_datacarbon_date_input'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacarbon',
            name='date_input',
        ),
    ]
