# Generated by Django 4.1 on 2022-10-27 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_remove_datacarbon_date_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbonkendaraandarat',
            name='date_input',
            field=models.DateField(default=datetime.date(2022, 10, 27)),
        ),
        migrations.AlterField(
            model_name='carbonlistrik',
            name='date_input',
            field=models.DateField(default=datetime.date(2022, 10, 27)),
        ),
    ]
