<<<<<<< HEAD
<<<<<<< HEAD
# Generated by Django 4.1 on 2022-10-28 14:09
=======
# Generated by Django 4.1 on 2022-10-28 17:41
>>>>>>> fb4a75d (Fix user object passing)
=======
# Generated by Django 4.1 on 2022-10-28 17:41
>>>>>>> 9e96eee (pull)

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ikutdonasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
